### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by siennathesane**
Referenced the environment variable for folks with smaller home drives.

### CODE REVIEW

**Comment by mxplusb** [comment]
I signed the CLA so hopefully it updates at some point...

**Comment by aemengo** [comment]
Hey, @mxplusb thanks for making this PR (and signing the CLA). This functionality though is already covered in FAQ here: 

https://github.com/cloudfoundry-incubator/cfdev/blob/master/FAQ.md#can-i-configure-the-working-directory

I'd be happy to merge your changes in if you provide a relative link to that entry. What do you think?

**Comment by mxplusb** [comment]
Oh, yeah that works, I didn't realise there was an extra doc.

**Comment by mxplusb** [comment]
@aemengo let me know if that works. :)

**Comment by aemengo** [comment]
Absolutely beautiful, thanks! ❤

**Pull request merged**
